[project]
name = "llm-chat-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiosmtplib>=5.1.0",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.115.14",
    "imapclient>=3.0.1",
    "langchain>=1.2.0",
    "langchain-cohere>=0.4.4",
    "langchain-community>=0.3.26",
    "langchain-groq>=1.1.1",
    "langchain-ollama>=0.3.3",
    "langchain-openai>=0.3.25",
    "langchain-qdrant>=0.2.1",
    "langgraph>=0.4.8",
    "langgraph-checkpoint-redis>=0.1.2",
    "psycopg2>=2.9.10",
    "psycopg[binary,pool]>=3.3.2",
    "pygithub>=2.8.1",
    "pyjwt[crypto]>=2.10.1",
    "python-dotenv>=1.1.0",
    "qdrant-client>=1.16.2",
    "sqlalchemy>=2.0.41",
]
